package com.vish.entity;
// Generated Sep 21, 2020 10:32:49 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name="student")
public class Student  implements java.io.Serializable {


     private Integer studentId;
     private String studentName;
     private String nic;
     private String password;
     private String gender;

    public Student() {
    }

    public Student(String studentName, String nic, String password, String gender) {
       this.studentName = studentName;
       this.nic = nic;
       this.password = password;
       this.gender = gender;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="studentId", unique=true, nullable=false)
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="StudentName", nullable=false)
    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    
    @Column(name="nIC", nullable=false, length=12)
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="gender", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


